### ISSUE TITLE
Не хватает сообщений об ошибках в json ответа

### ISSUE THREAD

**Issue by ProklUng** [crawler364/debug1c#2]
Добрый день. Покрутил компонент - хорошая работа, спасибо. Пара моментов:

1. В json ответах контроллера, даже в случае ошибки, всегда success. Оно логируется, да, но поначалу не очевидно. Скажем, 
    если добавить вот так:

        // TYPE_MODE
        if ($params['TYPE_MODE'] && $dataType = Json::decode(htmlspecialcharsback($params['TYPE_MODE']))) {
            $params = array_merge($params, $dataType);
        } else {
            $this->addError(new Error (Loc::getMessage('WC_DEBUG1C_MODE_NOT_SELECTED')));
            $this->add2log(Loc::getMessage('WC_DEBUG1C_MODE_NOT_SELECTED'));
            return null;
        }

   то становится IMHO лучше.

2. Эти раскопки стали следствием поиска способа запускать что-нибудь из функционала компонента в silence режиме. Например, в CLI командах или в обработчике брокера сообщений. Может у Вас есть соображения, как это можно сделать с минимальными трудозатратами?

Имею в виду, скажем, последовательность запросов к /bitrix/services/main/ajax.php дабы добиться импорта без формы.

**Comment by ProklUng** [comment]
Если интересно, то решил проблему (на скорую руку) так.

В итоге запрос выглядит так: /bitrix/services/main/ajax.php?mode=ajax&c=wc:debug1c&action=init&silence=Y&type=catalog&work=import&login=admin&password=admin

В getParams() файла ajax.php:

        $params = $this->request->toArray() ?: [];

        if ((string)$this->request->getQuery('silence') === 'Y') {
            $type = $this->request->getQuery('type') ?? 'catalog';
            $mode = (string)$this->request->getQuery('work');
            $params = [
                'TYPE_MODE' => json_encode(['TYPE' => $type, 'MODE' => $mode]),
                'EXCHANGE_URL' => $this->request->getQuery('exchange')
            ];
        }

И в createHttpClient():

        $unsignedParameters = $this->getUnsignedParameters();

        if ((string)$this->request->getQuery('silence') === 'Y') {
            $login = (string)$this->request->getQuery('login');
            $password = (string)$this->request->getQuery('password');
            $unsignedParameters = ['LOGIN' => $login, 'PASSWORD' => $password];
        }

Все запускается и отрабатывает.

**Comment by crawler364** [comment]
> Добрый день. Покрутил компонент - хорошая работа, спасибо. Пара моментов:
> 
> 1. В json ответах контроллера, даже в случае ошибки, всегда success. Оно логируется, да, но поначалу не очевидно. Скажем,
>    если добавить вот так:
>    ```
>     // TYPE_MODE
>     if ($params['TYPE_MODE'] && $dataType = Json::decode(htmlspecialcharsback($params['TYPE_MODE']))) {
>         $params = array_merge($params, $dataType);
>     } else {
>         $this->addError(new Error (Loc::getMessage('WC_DEBUG1C_MODE_NOT_SELECTED')));
>         $this->add2log(Loc::getMessage('WC_DEBUG1C_MODE_NOT_SELECTED'));
>         return null;
>     }
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    то становится IMHO лучше.
> 2. Эти раскопки стали следствием поиска способа запускать что-нибудь из функционала компонента в silence режиме. Например, в CLI командах или в обработчике брокера сообщений. Может у Вас есть соображения, как это можно сделать с минимальными трудозатратами?
> 
> Имею в виду, скажем, последовательность запросов к /bitrix/services/main/ajax.php дабы добиться импорта без формы.

Привет, спасибо :)
1. Добавил соответствующие ответы в контроллер. 
2. Интересная задача, никогда не думал его так использовать.

**Comment by crawler364** [comment]
> Если интересно, то решил проблему (на скорую руку) так.
> 
> В итоге запрос выглядит так: /bitrix/services/main/ajax.php?mode=ajax&c=wc:debug1c&action=init&silence=Y&type=catalog&work=import&login=admin&password=admin
> 
> В getParams() файла ajax.php:
> 
> ```
>     $params = $this->request->toArray() ?: [];
> 
>     if ((string)$this->request->getQuery('silence') === 'Y') {
>         $type = $this->request->getQuery('type') ?? 'catalog';
>         $mode = (string)$this->request->getQuery('work');
>         $params = [
>             'TYPE_MODE' => json_encode(['TYPE' => $type, 'MODE' => $mode]),
>             'EXCHANGE_URL' => $this->request->getQuery('exchange')
>         ];
>     }
> ```
> 
> И в createHttpClient():
> 
> ```
>     $unsignedParameters = $this->getUnsignedParameters();
> 
>     if ((string)$this->request->getQuery('silence') === 'Y') {
>         $login = (string)$this->request->getQuery('login');
>         $password = (string)$this->request->getQuery('password');
>         $unsignedParameters = ['LOGIN' => $login, 'PASSWORD' => $password];
>     }
> ```
> 
> Все запускается и отрабатывает.

Спасибо за решение, если будет время на неделе добавлю это в компонент, хотя тут уже напрашивается модуль)

**Comment by ProklUng** [comment]
Я форканул Ваш пакет (https://github.com/ProklUng/debug1c) и сделал там чуть иначе - ввел отдельный action контроллера silence. Ну и малек пришлось подработать напильником ;-)

А модуль да, напрашивается.

**Comment by ProklUng** [comment]
Переделал свой форк под Ваши последние изменения.

Хорошо бы логгер вынести в отдельный класс IMHO. Он так нехорошо размазан и намертво пришит.
